pages:
  stage: deploy
  environment: production
  script:
    - echo "Déploiement de CodePM depuis le dossier public"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
