#!/bin/bash
echo "=== Creating Asset Directories ==="
mkdir -p images

echo "=== Setting Up Image Assets ==="
cat > images/mystuff.png << EOL
iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAL5SURBVGiB7ZhNaBNBGIbfmd1sG5PWpgYF/6AUFcSDFg+KB0WwJwUP/kBBQaF4EL2qeBJERInoScSDICIIXgQvKoInQVHwIggepIjFg1VrTbFptibZ3R0P1aDZ7MzuJtlsFJ8QAvN98877zH47u5MEyJEjR44c/zNk6wONJZu1Wq2pZhXV6oFisej0i3e8kCuXy1uiKNohhHhACHHjOE4hYcwkY+wNpfROEATPZr/rdrulcrlsfQHYvFB7e3v7ZBzHZ6IoenvgwIFVHR0dZHBwsLKwsECWl5cL/f39yw8fPlwbx/ERKeVhAHcBYGxsbE0YhtullGustVZKqRZCVCmlNwDcBBD2er29lNJRznmPUurk5OTkhfHx8asAUKlUHtu2r8zPz789dOhQwff9q4SQd1EUnZ+amnoLAJZlGUopRyl1pZSbAbzSWkf9/f3LjDHOGHsZx/G1arX6l+cXLVp0kVLaLoQ4AuDXDvTZGv1zMpmBZrN5jnN+Rim1B8DbTC5okBBiqYlW1U0RiZkzmYFms3mUc35GSrmHUvoms6sZQCm1TLSHcRx/SWJ+KgNhGB7jnJ9SSu2llE5nfsV0EUrpWhPtYRRFn5LYX9QApdSxbftUFEX7KKUfc+LkAqW0YCKOjo7WkthfZAHzlFLHtu3TURTtJ4TNZHaxOZRSC020+4SQ+ST2zZYXAA5TSp9kdrE5lBDCRHtACFmfxD6t+M2fEkLu/I0rmsMY65RSvk9if/EPOpLSP2+jm80AAPBGo7GBUro6if2P3YV2ttoNAFpraq3tpJQ+tdY2TSu4TindBOBLEn+a1SfzEEJsxtj7tPFa66+1Wm1SGGNzlUrFNRm01vOc8412q/0AgNnZ2S+MMUdKeVC2SFEAsCilgRCinSS0W1prVq/XL0kp3yaJFUKwIAiOm+RSylgI0UYp/Z5GRyn1tdY/pJS7CSE1k0FrPRFF0R3P8z76vr8hTawxA4yxKSnlPqXU96GhoZtKqa/GICHmwzB8PDMz82BiYsJhjLGk8QDQ19dX8H3/WLVavZ5GzJEjR44cOXL8W/wAR+p1T44T+xoAAAAASUVORK5CYII=
EOL

# Installation des dépendances principales
npm install

# Aller dans le répertoire scratch-blocks et installer les dépendances
cd ./node_modules/scratch-blocks
npm install

# Construction de scratch-blocks avec Python
python build.py

# Revenir à la racine du projet
cd ../..

# Ajout des extensions
node ./scripts/postinstall.js

# Construction du projet
NODE_ENV=production BUILD_MODE=dist NODE_OPTIONS="--max-old-space-size=8192" npm run build
